package swagger

import (
	_ "github.com/ether/etherpad-go/docs"
	swagger "github.com/gofiber/contrib/v3/swaggo"
	"github.com/gofiber/fiber/v3"
)

// Init registers the Swagger UI route
// The Swagger documentation is part of the binary through the import of github.com/ether/etherpad-go/docs
// The docs package is automatically embedded in the binary through the _ import
func Init(app *fiber.App) {
	// Serve Swagger UI at /swagger/*
	// The swagger.json/yaml are loaded from the docs package generated by swag init
	app.Get("/swagger/*", swagger.New(swagger.Config{
		DeepLinking:  true,
		DocExpansion: "list",
	}))
}
