/**
 * Plugin Build Script
 *
 * Dieses Script scannt das plugins/-Verzeichnis nach Plugin-Definitionen
 * und generiert eine aktualisierte plugin_registry.ts mit allen client_hooks Modulen.
 *
 * Verwendung: node scripts/build-plugins.js
 */

import * as fs from 'node:fs';
import * as path from 'node:path';

const PLUGINS_DIR = '../plugins';
const ASSETS_EP_JSON = '../assets/ep.json';
const REGISTRY_OUTPUT = './src/js/pluginfw/plugin_registry.ts';

interface Part {
  name: string;
  hooks?: Record<string, string>;
  client_hooks?: Record<string, string>;
  plugin?: string;
  full_name?: string;
}

interface PluginDef {
  parts: Part[];
}

interface ClientPluginDef {
  plugins: Record<string, string>;
  parts: Part[];
}

/**
 * Lädt die ep.json eines Plugins
 */
function loadPluginDef(pluginPath: string): PluginDef | null {
  try {
    const content = fs.readFileSync(pluginPath, 'utf-8');
    return JSON.parse(content);
  } catch (err) {
    console.error(`Failed to load plugin definition from ${pluginPath}:`, err);
    return null;
  }
}

/**
 * Collects unique module paths and plugin names from client_hooks definitions.
 */
function collectClientHooksModules(parts: Part[]): { modules: Map<string, string>; pluginNames: Set<string> } {
  const modules = new Map<string, string>();
  const pluginNames = new Set<string>();

  for (const part of parts) {
    if (part.client_hooks) {
      if (part.plugin) pluginNames.add(part.plugin);
      for (const [, hookPath] of Object.entries(part.client_hooks)) {
        const modulePath = hookPath.split(':')[0];
        modules.set(modulePath, modulePath);
      }
    }
  }

  return { modules, pluginNames };
}

/**
 * Konvertiert einen Plugin-Modul-Pfad zu einem relativen Require-Pfad
 */
function modulePathToRequirePath(modulePath: string): string {
  // ep_etherpad-lite/static/js/messageHandler -> ../messageHandler
  if (modulePath.startsWith('ep_etherpad-lite/static/js/')) {
    const localPath = modulePath.replace('ep_etherpad-lite/static/js/', '');
    return `../${localPath}`;
  }

  // Externe Plugins: ep_example/static/js/index -> ../../plugins/ep_example/static/js/index
  // Diese werden dynamisch geladen, nicht gebündelt
  return null;
}

/**
 * Generates the plugin_registry.ts file.
 * Plugins are self-initializing via EventBus subscriptions — importing them
 * triggers their side effects. No hook-to-function mapping is needed.
 */
function generatePluginRegistry(modules: Map<string, string>, pluginNames: Set<string>): string {
  const sideEffectImports: string[] = [];

  Array.from(modules.entries()).forEach(([modulePath]) => {
    const requirePath = modulePathToRequirePath(modulePath);
    if (requirePath) {
      sideEffectImports.push(`import '${requirePath}'`);
    }
  });

  const pluginEntries: string[] = [];
  for (const name of pluginNames) {
    pluginEntries.push(`  '${name}': true,`);
  }

  return `// @ts-nocheck
/**
 * Plugin Registry - Imports all plugin modules
 *
 * AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
 * Generated by: scripts/build-plugins.ts
 */

// Import plugins (side-effect: each plugin self-registers via EventBus)
${sideEffectImports.join('\n')}

// Plugin metadata for the admin/settings UI
export const pluginModules: Record<string, boolean> = {
${pluginEntries.join('\n')}
}
`;
}

/**
 * Generiert die plugin-definitions.json Datei
 */
function generatePluginDefinitions(plugins: Map<string, string>, parts: Part[]): ClientPluginDef {
  return {
    plugins: Object.fromEntries(plugins),
    parts: parts,
  };
}

/**
 * Hauptfunktion
 */
function main() {
  const allParts: Part[] = [];
  const allPlugins = new Map<string, string>();

  // 1. Lade das Core-Plugin (ep_etherpad-lite)
  const corePluginPath = path.resolve(__dirname, ASSETS_EP_JSON);
  const corePlugin = loadPluginDef(corePluginPath);

  if (corePlugin) {
    allPlugins.set('ep_etherpad-lite', '1.8.13');
    for (const part of corePlugin.parts) {
      part.plugin = 'ep_etherpad-lite';
      part.full_name = `ep_etherpad-lite/${part.name}`;
      allParts.push(part);
    }
  }

  // 2. Lade externe Plugins aus dem plugins/-Verzeichnis
  const pluginsDir = path.resolve(__dirname, PLUGINS_DIR);
  if (fs.existsSync(pluginsDir)) {
    const entries = fs.readdirSync(pluginsDir, { withFileTypes: true });

    for (const entry of entries) {
      if (entry.isDirectory()) {
        const pluginName = entry.name;
        const epJsonPath = path.join(pluginsDir, pluginName, 'ep.json');

        if (fs.existsSync(epJsonPath)) {
          const pluginDef = loadPluginDef(epJsonPath);
          if (pluginDef) {
            allPlugins.set(pluginName, '0.0.1');
            for (const part of pluginDef.parts) {
              part.plugin = pluginName;
              part.full_name = `${pluginName}/${part.name}`;
              allParts.push(part);
            }
          }
        }
      }
    }
  }

  // 3. Collect all client_hooks modules and plugin names
  const { modules: clientHooksModules, pluginNames } = collectClientHooksModules(allParts);

  // 4. Generate plugin_registry.ts
  const registryContent = generatePluginRegistry(clientHooksModules, pluginNames);
  const registryPath = path.resolve(__dirname, REGISTRY_OUTPUT);
  fs.writeFileSync(registryPath, registryContent);
  console.log(`Generated: ${registryPath}`);

  // 5. Generate plugin-definitions.json
  const pluginDefs = generatePluginDefinitions(allPlugins, allParts);
  const pluginDefsPath = path.resolve(__dirname, PLUGINS_DIR, 'plugin-definitions.json');
  fs.writeFileSync(pluginDefsPath, JSON.stringify(pluginDefs, null, 2));
  console.log(`Generated: ${pluginDefsPath}`);

  console.log(`\nRegistered ${allPlugins.size} plugin(s) with ${allParts.length} part(s)`);
  console.log(`Found ${clientHooksModules.size} client_hooks module(s)`);
}

main();

