package hooks

const PadDefaultContentString = "padDefaultContent"
const PreAuthorizeString = "preAuthorize"
const PreAuthzFailureString = "preAuthzFailure"
const PadLoadString = "padLoad"
const PadCreateString = "padCreate"
const PadUpdateString = "padUpdate"
const PadCopyString = "padCopy"
const PadRemoveString = "padRemove"
const HandleMessageString = "handleMessage"
const HandleMessageSecurityString = "handleMessageSecurity"
const ClientReadyString = "clientReady"
const ClientVarsString = "clientVars"
const ChatNewMessageString = "chatNewMessage"
const UserJoinString = "userJoin"
const UserLeaveString = "userLeave"
