// @ts-nocheck
/**
 * Plugin Registry - Imports all plugin modules
 *
 * AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
 * Generated by: build.js
 */

// Import plugins (side-effect: each plugin self-registers via EventBus)
import '../messageHandler'
import '../../../../plugins/ep_align/static/js/index'
import '../../../../plugins/ep_author_hover/static/js/index'
import '../../../../plugins/ep_chat_log_join_leave/static/js/index'
import '../../../../plugins/ep_clear_formatting/static/js/index'
import '../../../../plugins/ep_cursortrace/static/js/index'
import '../../../../plugins/ep_font_color/static/js/index'
import '../../../../plugins/ep_font_family/static/js/index'
import '../../../../plugins/ep_font_size/static/js/index'
import '../../../../plugins/ep_heading/static/js/index'
import '../../../../plugins/ep_heading/static/js/shared'
import '../../../../plugins/ep_markdown/static/js/markdown'
import '../../../../plugins/ep_print/static/js/index'
import '../../../../plugins/ep_spellcheck/static/js/index'
import '../../../../plugins/ep_table_of_contents/static/js/index'

// Plugin metadata for the admin/settings UI
export const pluginModules: Record<string, boolean> = {
  'ep_etherpad-lite': true,
  'ep_align': true,
  'ep_author_hover': true,
  'ep_chat_log_join_leave': true,
  'ep_clear_formatting': true,
  'ep_cursortrace': true,
  'ep_font_color': true,
  'ep_font_family': true,
  'ep_font_size': true,
  'ep_heading': true,
  'ep_markdown': true,
  'ep_print': true,
  'ep_spellcheck': true,
  'ep_table_of_contents': true,
}
