// @ts-nocheck
/**
 * Plugin Registry - Conditional plugin loading
 *
 * AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
 * Generated by: build.js
 */

// Core modules — always loaded
import '../messageHandler';

// Dynamic import map — plugins are loaded only when enabled
const pluginLoaders: Record<string, () => Promise<any>> = {
  'ep_align': () => Promise.all([import('../../../../plugins/ep_align/static/js/index')]),
  'ep_author_hover': () => Promise.all([import('../../../../plugins/ep_author_hover/static/js/index')]),
  'ep_chat_log_join_leave': () => Promise.all([import('../../../../plugins/ep_chat_log_join_leave/static/js/index')]),
  'ep_clear_formatting': () => Promise.all([import('../../../../plugins/ep_clear_formatting/static/js/index')]),
  'ep_cursortrace': () => Promise.all([import('../../../../plugins/ep_cursortrace/static/js/index')]),
  'ep_font_color': () => Promise.all([import('../../../../plugins/ep_font_color/static/js/index')]),
  'ep_font_family': () => Promise.all([import('../../../../plugins/ep_font_family/static/js/index')]),
  'ep_font_size': () => Promise.all([import('../../../../plugins/ep_font_size/static/js/index')]),
  'ep_heading': () => Promise.all([import('../../../../plugins/ep_heading/static/js/index'), import('../../../../plugins/ep_heading/static/js/shared')]),
  'ep_markdown': () => Promise.all([import('../../../../plugins/ep_markdown/static/js/markdown')]),
  'ep_print': () => Promise.all([import('../../../../plugins/ep_print/static/js/index')]),
  'ep_spellcheck': () => Promise.all([import('../../../../plugins/ep_spellcheck/static/js/index')]),
  'ep_table_of_contents': () => Promise.all([import('../../../../plugins/ep_table_of_contents/static/js/index')]),
};

// Plugin metadata for the admin/settings UI
export const pluginModules: Record<string, boolean> = {
  'ep_etherpad-lite': true,
  'ep_align': true,
  'ep_author_hover': true,
  'ep_chat_log_join_leave': true,
  'ep_clear_formatting': true,
  'ep_cursortrace': true,
  'ep_font_color': true,
  'ep_font_family': true,
  'ep_font_size': true,
  'ep_heading': true,
  'ep_markdown': true,
  'ep_print': true,
  'ep_spellcheck': true,
  'ep_table_of_contents': true,
};

/**
 * Load only the enabled plugins. Call this after clientVars are available.
 * @param enabledPlugins - set of plugin names to load, or null to load all
 */
export async function loadEnabledPlugins(enabledPlugins?: Set<string> | null): Promise<void> {
  const promises: Promise<any>[] = [];
  for (const [name, loader] of Object.entries(pluginLoaders)) {
    if (enabledPlugins == null || enabledPlugins.has(name)) {
      promises.push(loader().catch(err => console.error(`Failed to load plugin ${name}:`, err)));
    }
  }
  await Promise.all(promises);
}
