import * as esbuild from 'esbuild';
import * as fs from "node:fs";
import * as path from "node:path";
import {execSync, spawn} from "node:child_process";

const run = (command, cwd) => {
  execSync(command, {
    cwd,
    stdio: "inherit",
  });
};

// ========================================
// Plugin Registry Generator
// ========================================

const PLUGINS_DIR = '../plugins';
const ASSETS_EP_JSON = '../assets/ep.json';
const REGISTRY_OUTPUT = './src/js/pluginfw/plugin_registry.ts';

/**
 * Lädt die ep.json eines Plugins
 */
function loadPluginDef(pluginPath) {
  try {
    const content = fs.readFileSync(pluginPath, 'utf-8');
    return JSON.parse(content);
  } catch (err) {
    console.error(`Failed to load plugin definition from ${pluginPath}:`, err);
    return null;
  }
}

/**
 * Collects unique module paths and plugin names from client_hooks definitions.
 * For EventBus-based plugins, we only need the module paths (for imports)
 * and plugin names (for metadata).
 */
function collectClientHooksModules(parts) {
  const modules = new Map();
  const pluginNames = new Set();

  for (const part of parts) {
    if (part.client_hooks) {
      if (part.plugin) pluginNames.add(part.plugin);
      for (const [, hookPath] of Object.entries(part.client_hooks)) {
        const modulePath = hookPath.split(':')[0];
        modules.set(modulePath, modulePath);
      }
    }
  }

  return { modules, pluginNames };
}

/**
 * Konvertiert einen Plugin-Modul-Pfad zu einem relativen Require-Pfad
 * Der Pfad ist relativ zu src/js/pluginfw/ wo die plugin_registry.ts liegt
 */
function modulePathToRequirePath(modulePath) {
  if (modulePath.startsWith('ep_etherpad-lite/static/js/')) {
    const localPath = modulePath.replace('ep_etherpad-lite/static/js/', '');
    return `../${localPath}`;
  }

  // Externe Plugins: ep_align/static/js/index -> ../../../../plugins/ep_align/static/js/index
  // Von src/js/pluginfw/ aus: ../../../ geht zu ui/, dann ../plugins/
  const pluginMatch = modulePath.match(/^(ep_[^/]+)\/static\/js\/(.+)$/);
  if (pluginMatch) {
    const [, pluginName, jsPath] = pluginMatch;
    return `../../../../plugins/${pluginName}/static/js/${jsPath}`;
  }

  return null;
}

/**
 * Generates the plugin_registry.ts file.
 * Plugins are self-initializing via EventBus subscriptions — importing them
 * triggers their side effects. No hook-to-function mapping is needed.
 */
function generatePluginRegistry(modules, pluginNames) {
  // Map plugin name -> list of require paths for that plugin
  const pluginImports = new Map();
  for (const [modulePath] of modules) {
    const pluginMatch = modulePath.match(/^(ep_[^/]+)\//);
    if (!pluginMatch) continue;
    const pluginName = pluginMatch[1];
    const requirePath = modulePathToRequirePath(modulePath);
    if (!requirePath) continue;
    if (!pluginImports.has(pluginName)) pluginImports.set(pluginName, []);
    pluginImports.get(pluginName).push(requirePath);
  }

  // Core module imports (ep_etherpad-lite) — always loaded
  const coreImports = [];
  for (const [modulePath] of modules) {
    if (!modulePath.startsWith('ep_etherpad-lite/')) continue;
    const requirePath = modulePathToRequirePath(modulePath);
    if (requirePath) coreImports.push(`import '${requirePath}';`);
  }

  // Build the dynamic import map for external plugins
  const importEntries = [];
  for (const [pluginName, paths] of pluginImports) {
    if (pluginName === 'ep_etherpad-lite') continue;
    const imports = paths.map(p => `import('${p}')`).join(', ');
    importEntries.push(`  '${pluginName}': () => Promise.all([${imports}]),`);
  }

  const pluginEntries = [];
  for (const name of pluginNames) {
    pluginEntries.push(`  '${name}': true,`);
  }

  return `// @ts-nocheck
/**
 * Plugin Registry - Conditional plugin loading
 *
 * AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
 * Generated by: build.js
 */

// Core modules — always loaded
${coreImports.join('\n')}

// Dynamic import map — plugins are loaded only when enabled
const pluginLoaders: Record<string, () => Promise<any>> = {
${importEntries.join('\n')}
};

// Plugin metadata for the admin/settings UI
export const pluginModules: Record<string, boolean> = {
${pluginEntries.join('\n')}
};

/**
 * Load only the enabled plugins. Call this after clientVars are available.
 * @param enabledPlugins - set of plugin names to load, or null to load all
 */
export async function loadEnabledPlugins(enabledPlugins?: Set<string> | null): Promise<void> {
  const promises: Promise<any>[] = [];
  for (const [name, loader] of Object.entries(pluginLoaders)) {
    if (enabledPlugins == null || enabledPlugins.has(name)) {
      promises.push(loader().catch(err => console.error(\`Failed to load plugin \${name}:\`, err)));
    }
  }
  await Promise.all(promises);
}
`;
}

/**
 * Generiert die Plugin-Definitionen und Registry
 */
function buildPlugins() {
  const allParts = [];
  const allPlugins = new Map();
  const absWorkingDir = process.cwd();

  // 1. Lade das Core-Plugin (ep_etherpad-lite)
  const corePluginPath = path.resolve(absWorkingDir, ASSETS_EP_JSON);
  const corePlugin = loadPluginDef(corePluginPath);

  if (corePlugin) {
    allPlugins.set('ep_etherpad-lite', '1.8.13');
    for (const part of corePlugin.parts) {
      part.plugin = 'ep_etherpad-lite';
      part.full_name = `ep_etherpad-lite/${part.name}`;
      allParts.push(part);
    }
  }

  // 2. Lade externe Plugins aus dem plugins/-Verzeichnis
  const pluginsDir = path.resolve(absWorkingDir, PLUGINS_DIR);
  if (fs.existsSync(pluginsDir)) {
    const entries = fs.readdirSync(pluginsDir, { withFileTypes: true });

    for (const entry of entries) {
      if (entry.isDirectory()) {
        const pluginName = entry.name;
        const epJsonPath = path.join(pluginsDir, pluginName, 'ep.json');

        if (fs.existsSync(epJsonPath)) {
          const pluginDef = loadPluginDef(epJsonPath);
          if (pluginDef) {
            allPlugins.set(pluginName, '0.0.1');
            for (const part of pluginDef.parts) {
              part.plugin = pluginName;
              part.full_name = `${pluginName}/${part.name}`;
              allParts.push(part);
            }
          }
        }
      }
    }
  }

  // 3. Collect all client_hooks modules and plugin names
  const { modules: clientHooksModules, pluginNames } = collectClientHooksModules(allParts);

  // 4. Generate plugin_registry.ts
  const registryContent = generatePluginRegistry(clientHooksModules, pluginNames);
  const registryPath = path.resolve(absWorkingDir, REGISTRY_OUTPUT);
  fs.writeFileSync(registryPath, registryContent);
  console.log(`Generated: ${registryPath}`);

  // 5. Generate plugin-definitions.json
  const pluginDefs = {
    plugins: Object.fromEntries(allPlugins),
    parts: allParts,
  };
  const pluginDefsPath = path.resolve(absWorkingDir, PLUGINS_DIR, 'plugin-definitions.json');
  fs.writeFileSync(pluginDefsPath, JSON.stringify(pluginDefs, null, 2));
  console.log(`Generated: ${pluginDefsPath}`);

  console.log(`Registered ${allPlugins.size} plugin(s) with ${allParts.length} part(s)`);
  console.log(`Found ${clientHooksModules.size} client_hooks module(s)\n`);

  // Return for alias generation
  return { allPlugins, clientHooksModules };
}

// Generiere Plugin-Definitionen vor dem Build
console.log('Building plugin definitions...');
const { allPlugins, clientHooksModules } = buildPlugins();

// ========================================
// esbuild Configuration
// ========================================

const relativePath = 'ep_etherpad-lite/static/js';

const moduleResolutionPath = "./src/js"

// Basis-Aliase
const alias = {
    [`${relativePath}/ace2_inner`]: `${moduleResolutionPath}/ace2_inner`,
    [`${relativePath}/ace2_common`]: `${moduleResolutionPath}/ace2_common`,
    [`${relativePath}/pluginfw/client_plugins`]: `${moduleResolutionPath}/pluginfw/client_plugins`,
    [`${relativePath}/pluginfw/plugin_defs`]: `${moduleResolutionPath}/pluginfw/plugin_defs`,
    [`${relativePath}/pluginfw/hooks`]: `${moduleResolutionPath}/pluginfw/hooks`,
    [`${relativePath}/pluginfw/shared`]: `${moduleResolutionPath}/pluginfw/shared`,
    [`${relativePath}/core/EventBus`]: `${moduleResolutionPath}/core/EventBus`,
    [`${relativePath}/core/PluginBridge`]: `${moduleResolutionPath}/core/PluginBridge`,
    [`${relativePath}/core/PluginAPI`]: `${moduleResolutionPath}/core/PluginAPI`,
    [`${relativePath}/rjquery`]: `${moduleResolutionPath}/rjquery`,
    [`${relativePath}/nice-select`]: `${moduleResolutionPath}/vendors/nice-select`,
    // Client hooks module mappings
    [`${relativePath}/messageHandler`]: `${moduleResolutionPath}/messageHandler`,
    [`${relativePath}/pad`]: `${moduleResolutionPath}/pad`,
    [`${relativePath}/chat`]: `${moduleResolutionPath}/chat`,
    [`${relativePath}/pad_editbar`]: `${moduleResolutionPath}/pad_editbar`,
    [`${relativePath}/pad_impexp`]: `${moduleResolutionPath}/pad_impexp`,
    [`${relativePath}/collab_client`]: `${moduleResolutionPath}/collab_client`,
    [`${relativePath}/broadcast`]: `${moduleResolutionPath}/broadcast`,
    [`${relativePath}/broadcast_slider`]: `${moduleResolutionPath}/broadcast_slider`,
    [`${relativePath}/broadcast_revisions`]: `${moduleResolutionPath}/broadcast_revisions`,
    [`${relativePath}/colorutils`]: `${moduleResolutionPath}/colorutils`,
    [`${relativePath}/cssmanager`]: `${moduleResolutionPath}/cssmanager`,
    [`${relativePath}/pad_utils`]: `${moduleResolutionPath}/pad_utils`,
    [`${relativePath}/pad_cookie`]: `${moduleResolutionPath}/pad_cookie`,
    [`${relativePath}/pad_editor`]: `${moduleResolutionPath}/pad_editor`,
    [`${relativePath}/pad_userlist`]: `${moduleResolutionPath}/pad_userlist`,
    [`${relativePath}/pad_modals`]: `${moduleResolutionPath}/pad_modals`,
    [`${relativePath}/pad_savedrevs`]: `${moduleResolutionPath}/pad_savedrevs`,
    [`${relativePath}/pad_connectionstatus`]: `${moduleResolutionPath}/pad_connectionstatus`,
    [`${relativePath}/pad_automatic_reconnect`]: `${moduleResolutionPath}/pad_automatic_reconnect`,
    [`${relativePath}/scroll`]: `${moduleResolutionPath}/scroll`,
    [`${relativePath}/caretPosition`]: `${moduleResolutionPath}/caretPosition`,
    [`${relativePath}/security`]: `${moduleResolutionPath}/security`,
    [`${relativePath}/Changeset`]: `${moduleResolutionPath}/Changeset`,
    [`${relativePath}/AttributePool`]: `${moduleResolutionPath}/AttributePool`,
    [`${relativePath}/ace`]: `${moduleResolutionPath}/ace`,
    [`${relativePath}/timeslider`]: `${moduleResolutionPath}/timeslider`,
    [`${relativePath}/socketio`]: `${moduleResolutionPath}/socketio`,
    [`${relativePath}/skin_variants`]: `${moduleResolutionPath}/skin_variants`,
    [`${relativePath}/notifications`]: `${moduleResolutionPath}/notifications`
};

// Dynamisch Aliase für externe Plugins hinzufügen
for (const [modulePath] of clientHooksModules) {
  const pluginMatch = modulePath.match(/^(ep_[^/]+)\/static\/js\/(.+)$/);
  if (pluginMatch && !modulePath.startsWith('ep_etherpad-lite/')) {
    const [, pluginName, jsPath] = pluginMatch;
    alias[modulePath] = `../plugins/${pluginName}/static/js/${jsPath}`;
    console.log(`Added alias: ${modulePath} -> ../plugins/${pluginName}/static/js/${jsPath}`);
  }
}

const absWorkingDir = process.cwd()



const loaders = {
    '.woff': 'base64',
    '.woff2': 'base64',
    '.ttf': 'base64',
    '.eot': 'base64',
    '.svg': 'base64',
    '.png': 'base64',
    '.jpg': 'base64',
    '.gif': 'base64',
    '.otf': 'base64',
}

// ========================================
// Build Admin (React/Vite) — runs in parallel with esbuild
// ========================================

const buildAdmin = () => new Promise((resolve, reject) => {
  const isWindows = process.platform === 'win32';
  const cmd = isWindows ? 'pnpm.cmd' : 'pnpm';
  const adminDir = path.resolve(absWorkingDir, '..', 'admin');

  console.log('Building admin (React)...');
  const child = spawn(cmd, ['build'], { cwd: adminDir, stdio: 'inherit', shell: true });
  child.on('close', (code) => {
    if (code !== 0) reject(new Error(`Admin build failed with exit code ${code}`));
    else { console.log('Admin build complete.'); resolve(); }
  });
  child.on('error', reject);
});

// ========================================
// Run all builds in parallel
// ========================================

const esbuildOpts = { absWorkingDir, bundle: true, write: true, minify: true, metafile: true, target: 'es2020', sourcemap: true };

const results = await Promise.allSettled([
  // JS bundles
  esbuild.build({ ...esbuildOpts, entryPoints: ["./src/pad.js"], outdir: '../assets/js/pad/assets', alias, loader: loaders, logLevel: 'info' }),
  esbuild.build({ ...esbuildOpts, entryPoints: ["./src/welcome.js"], outdir: '../assets/js/welcome/assets', alias, loader: loaders, logLevel: 'info' }),
  esbuild.build({ ...esbuildOpts, entryPoints: ["./src/timeslider.js"], outdir: '../assets/js/timeslider/assets', alias, loader: loaders, logLevel: 'info' }),
  // CSS bundles
  esbuild.build({ ...esbuildOpts, entryPoints: ['../assets/css/skin/colibris/pad.css'], outdir: '../assets/css/build/skin/colibris', external: ['*.woff', '*.woff2', '*.ttf', '*.eot', '*.svg', '*.png', '*.jpg', '*.gif'], loader: loaders, logLevel: 'info' }),
  esbuild.build({ ...esbuildOpts, entryPoints: ['../assets/css/static/pad.css'], outdir: '../assets/css/build/static', external: ['*.woff', '*.woff2', '*.ttf', '*.eot', '*.svg', '*.png', '*.jpg', '*.gif', '/font/*', 'font/*'], loader: loaders, logLevel: 'info' }),
  // Admin React app (Vite)
  buildAdmin(),
]);

// Report failures
const failed = results.filter(r => r.status === 'rejected');
if (failed.length > 0) {
  for (const f of failed) console.error('Build error:', f.reason);
  process.exit(1);
}
